# fly.toml app configuration file generated for ollama-1-solitary-feather-1645 on 2024-07-14T09:34:15-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ollama-1-solitary-feather-1645'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
